[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts","@openzeppelin=lib/openzeppelin-contracts", "@solmate/=lib/solmate/src/"]
ffi = true
evm_version = 'paris'